version: '3.8'

services:
  payment-frontend:
      image: 'payment-frontend:latest'
      build:
        context: ./payment-system-frontend
        dockerfile: Dockerfile
      container_name: payment-frontend
      ports:
        - "3000:3000"
      depends_on:
        - payment-backend
  payment-backend:
    image: 'payment-backend:latest'
    build:
      context: ./payment-system-backend
    container_name: payment-backend
    depends_on:
      - db
      - broker
      - keycloak
    environment:
      - SPRING_DATASOURCE_DIALECT=org.hibernate.dialect.PostgreSQLDialect
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/payment_system
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=mysecretpassword
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_KAFKA_BOOTSTRAP_SERVER_HOST=broker
      - SPRING_KAFKA_BOOTSTRAP_SERVER_PORT=9092
      - LOG_LEVEL=INFO

    ports:
      - "8080:8080"

  db:
    image: 'postgres:latest'
    container_name: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_DB=payment_system
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  broker:
    image: 'apache/kafka:latest'
    container_name: broker
    ports:
      - "9092:9092"
  keycloak:
    image:  'quay.io/keycloak/keycloak:23.0.4'
    container_name: identity_provider
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    volumes:
      - ./keycloak:/opt/keycloak/data
    command:
      - "start-dev"
    ports:
      - "8081:8080"      
volumes:
  postgres_data: